---
# Playbook for TAK Server deployment only
# Usage: ansible-playbook playbooks/atak.yml

- name: Deploy TAK Server
  hosts: openmanet_devices
  gather_facts: yes
  become: no
  
  roles:
    - atak

